Fix teardown error on failed spec-resolution (#11)
When a test fails due to some error during spec resolution, an
unexpected error is thrown:

UnboundLocalError: local variable 'resolved' referenced during
assignment

Fix it.